### PR TITLE
add new web fadli7 

### PR DESCRIPTION
**Pull request by fadlifarham**
#30

### CODE REVIEW

**Comment by yuvraajnarula** [comment]
Can you pls share the screenshot of your code @fadli7

**Comment by yuvraajnarula** [comment]
can you pls share the screenshot of the working of your code @fadli7

**Comment by fadlifarham** [comment]
okay this is the screenshot

image

**Comment by fadlifarham** [comment]
Hi, can you add a Hacktoberfest-accepted label to this PR?
Thank you very much

**Pull request merged**
