### PR TITLE
portfolio website

### PR DESCRIPTION
**Pull request by hmmonotone**
@ion05  This is the pull request for issue #10. I have only used HTML and CSS but no JavaScript. 
This is the deployed version: https://hmmonotone.github.io/website-for-company/

### CODE REVIEW

**Comment by ion05** [comment]
Amazingg Website!

**Comment by ion05** [comment]
Please dont delete the basic 3 files present outside of your folder. Create index.html , index.css and index.js outside ur folder with the basic code. The code is there in this repo only

**Comment by hmmonotone** [comment]
So do I have to send another PR or have you updated it already?
@ion05

**Comment by ion05** [comment]
Please update ur own repo nd then open another PR

**Comment by hmmonotone** [comment]
Sure

**Pull request merged**
