### PR TITLE
Responding to #1

### PR DESCRIPTION
**Pull request by raj5036**
Created required files and further working in regards to #5

### CODE REVIEW

**Comment by ion05** [comment]
Ok keep working on it

**Comment by raj5036** [comment]
Okay.

**Comment by raj5036** [comment]
Please review the changes.

**Comment by ion05** [comment]
If you are doing this for hacktoberfest , please open the PR again in October only. And I need you to host your site on GitHub pages

**Comment by raj5036** [comment]
Yes I am doing it for Hacktober. Okay I will open the PR again in October and host it on GitHub Pages.

**Comment by ion05** [comment]
I am closing this PR then.

**Comment by raj5036** [comment]
Should I open the PR today?

And should I host it on GitHub Pages before you merge my PR or after it?

**Pull request closed without merging**
