### PR TITLE
Website COVID-19 #6

### PR DESCRIPTION
**Pull request by a-rfl**
Created a website with the rules to stay safe during this period of Covid-19.

### CODE REVIEW

**Comment by a-rfl** [comment]
I don't know if this is what it was needed... It's a really simple website.

**Comment by ion05** [comment]
Please host your own forked repo on github pages and if you are doing this for HacktoberFest 2020, open the repo after October 1st

**Comment by a-rfl** [comment]
I did forked it but but I must have mixed it all. Should I close this pull request  and restart on the froked version ?
Really sorry for the inconvenience...

**Comment by ion05** [comment]
Close this PR and open a new one

**Pull request closed without merging**
