### PR TITLE
Fix some UI issues and improve UI of the website

### PR DESCRIPTION
**Pull request by meerhamzadev**
#7 Improve UI of the website, hope you like :)

### CODE REVIEW

**Comment by ion05** [comment]
Please ref the issue you are solving

**Comment by meerhamzadev** [comment]
Actually, i improve the text color scheme of the website and also improve view of last portion by changing its width. Its Abbir-24's covid website.

**Comment by yuvraajnarula** [comment]
can you pls share the screenshot of the UI @MeerHamza1421

**Comment by meerhamzadev** [comment]
Yeah sure

**Comment by meerhamzadev** [comment]
Untitled
Untitled1
Untitled2 

 The color of the text before, is something similar to yellow i changed it to white. 

Untitled3

And in this section they both have less width so they look squeezed i increased some width of them.

**Pull request merged**
